//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNotification
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsRead { get; set; }
        public Nullable<int> AssociatedTaskId { get; set; }
    
        public virtual AppTask AppTask { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
